### ISSUE TITLE
Project Features Checklist 

### ISSUE THREAD

**Issue by NietZteiN** [UTDallasEPICS/UTDesign-Procurement#15]
The following is meant to be a complete list of features that should be implemented in the web application. Check off features as they are implemented. Features with bugs have links to their respective issues. 

# UTD Procurement Manager Application Features Checklist

## General Features
**Login Page**
- [ ] Sign in with UTD SSO.

## Student Features
- **Request Form**
  - [x] Fill out request information (date needed, additional details).
  - [x] Upload files (e.g., design specifications).
- **Reimbursement Form**
  - [x] Fill out reimbursement information.
  - [x] Upload receipts for verification.
- **Orders Page**
  - [x] View submitted requests.
  - [ ] Edit and resubmit rejected requests.
- **Order History Page**
  - [ ] View project information.
  - [x] View user information (mentors and students in the project).
  - [ ] View processed request/reimbursement information.

## Mentor Features
- **Orders & Reimbursements Page**
  - [x] View submitted requests/reimbursements.
  - [x] Approve or reject requests/reimbursements with comments for rejection reasons.
- **Projects & Order History Page**
  - [x] View project information.
  - [x] View user information.
  - [x] View processed request/reimbursement information.

## Admin Features
- **Orders & Reimbursements Page**
  - [ ] Process requests/reimbursements.
  - [x] Edit request/reimbursement data.
  - [x] Add/delete parts, expenses, and orders.
- **Projects & Order History Page**
  - [x] Edit project information.
  - [x] Edit user information.
  - [ ] Edit request/reimbursement data.
  - [ ] Add/delete parts, expenses, and orders.
- **Database Updates Page**
  - [x] Upload Excel files for adding/modifying data (users, projects, etc.).
  - [x] Add/delete users and projects.
